application: tripnomads
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

# Twitter Bootstrap
- url: /bootstrap-4.0.0-alpha.2
  static_dir: bootstrap-4.0.0-alpha.2

- url: /post
  script: travelNomads.app
  login: required

- url: /profile
  script: travelNomads.app
  login: required
  
- url: /.*
  script: travelNomads.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
